name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5
        with:
          php_version: "8.0"

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          TEST_NAME: Scarlett
        with:
          version: 8.5
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
          php_version: "8.0"
